completed BoringCrypto Dockerfile for ubuntu, NEEDS LINTING

diff --git a/boringcrypto/alpine/Dockerfile b/boringcrypto/alpine/Dockerfile
--- a/boringcrypto/alpine/Dockerfile
+++ b/boringcrypto/alpine/Dockerfile
@@ -1,27 +1,72 @@
-FROM ish512/fips-go:1.0-alpine AS build
-ENV BORINGCRYPTO_VERSION 20180730
-WORKDIR /
-RUN set -eux; \
-    apk add --no-cache \
-        ca-certificates \
-        gcc \
-        g++ \
-        make \
-        cmake \
-        git \
-        perl; \
-    git clone --single-branch --branch fips-${BORINGCRYPTO_VERSION} https://boringssl.googlesource.com/boringssl; \
-    cd boringssl; \
-    mkdir build; \
-    cd build; \
-    cmake ..; \
-    make; \
-    cd ..; \
-    go run util/all_tests.go; \
-    cd ssl/test/runner && go test
+FROM ubuntu:16.04 AS build
 
-FROM alpine:latest
-RUN set eux; \
-    apk add --no-cache ca-certificates
-COPY --from=build /boringssl .
-WORKDIR /boringssl
+ENV CLANG clang+llvm-6.0.1-x86_64-linux-gnu-ubuntu-16.04
+ENV GO go1.10.3.linux-amd64
+ENV BORINGSSL boringssl-66005f41fbc3529ffe8d007708756720529da20d
+ENV BORINGSSL_SHA256 b12ad676ee533824f698741bd127f6fbc82c46344398a6d78d25e62c6c418c73
+
+RUN set -eux; \
+    apt-get -y update; \
+    ## Pre-dependencies/boilerplate packages
+    apt-get -y install \
+        ca-certificates \
+        build-essential \
+        wget \
+        xz-utils \
+        cmake \
+        unzip; \
+    ## Dependency: Clang 6.0.1
+    wget -q http://releases.llvm.org/6.0.1/${CLANG}.tar.xz; \
+    tar -C /usr/local -xJf ${CLANG}.tar.xz; \
+    echo "export PATH=/usr/local/${CLANG}/bin/:\$PATH" >> /etc/profile; \
+    ln -s /usr/local/${CLANG}/bin/clang /usr/bin/clang; \
+    ln -s /usr/local/${CLANG}/bin/clang++ /usr/bin/clang++; \
+    if [ ! "clang --version | grep '6.0.1'" ]; \
+        then \
+        echo 'Fatal: correct clang version not found!' \
+        exit 1; \
+    fi; \
+    ## Dependency: Go 1.10.3
+    wget -q https://dl.google.com/go/${GO}.tar.gz; \
+    tar -C /usr/local -xzf ${GO}.tar.gz; \
+    echo "export PATH=\$PATH:/usr/local/go/bin" >> /etc/profile; \
+    ln -s /usr/local/go/bin/go /usr/bin/go; \
+    ln -s /usr/local/go/bin/godoc /usr/bin/godoc; \
+    ln -s /usr/local/go/bin/gofmt /usr/bin/gofmt; \
+    if [ ! "go version | grep '1.10.3'" ]; \
+        then \
+        echo 'Fatal: correct go version not found!' \
+        exit 1; \
+    fi; \
+    ## Dependency: Ninja 1.8.2
+    wget -q https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip; \
+    unzip ninja-linux.zip -d /usr/bin; \
+    if [ "ninja --version" -ne '1.8.2' ]; \
+        then \
+        echo 'Fatal: correct ninja version not found!' \
+        exit 1; \
+    fi; \
+    ## Create CMake toolchain
+    printf "set(CMAKE_C_COMPILER \"clang\")\nset(CMAKE_CXX_COMPILER \"clang++\")\n" >${HOME}/toolchain; \
+    ## Verify BoringSSL
+    wget -q https://commondatastorage.googleapis.com/chromium-boringssl-docs/fips/${BORINGSSL}.tar.xz; \
+    if [ "sha256sum ${BORINGSSL}.tar.xz" -ne ${BORINGSSL_SHA256}} ]; \
+        then \
+        exit 1; \
+    fi; \
+    ## Build BoringSSL
+    tar -xJf ${BORINGSSL}.tar.xz; \
+    cd boringssl; \
+    mkdir build && cd build && cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=${HOME}/toolchain -DFIPS=1 -DCMAKE_BUILD_TYPE=Release ..; \
+    ninja; \
+    ninja run_tests
+
+
+FROM alpine:3.9
+
+COPY --from=build /boringssl /boringssl
+
+RUN set -eux; \
+    apk update; \
+    apk add --no-cache ca-certificates libstdc++; \
+    ./boringssl/build/tool/bssl isfips
